// Package mealplan implements the Meal Planning module (Phase 5): weekly grids
// of meal slots (breakfast/lunch/dinner/snack per day), each slot optionally
// referencing a recipe (Phase 5a). A shopping list is generated by aggregating
// the ingredients of all slotted recipes.
package mealplan

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

// MealType is one of the four daily meal slots.
type MealType string

const (
	MealBreakfast MealType = "breakfast"
	MealLunch     MealType = "lunch"
	MealDinner    MealType = "dinner"
	MealSnack     MealType = "snack"
)

func (m MealType) Valid() bool {
	switch m {
	case MealBreakfast, MealLunch, MealDinner, MealSnack:
		return true
	default:
		return false
	}
}

// MealSlot is a single time-blocked slot in the plan.
type MealSlot struct {
	ID       string
	Date     time.Time
	MealType MealType
	RecipeID *string // nil = no recipe assigned
	Notes    string
}

// ShoppingItem is one line of the generated shopping list.
type ShoppingItem struct {
	ID              string
	IngredientName  string
	QuantityAgg     string
	Unit            string
	IsChecked       bool
}

// MealPlan is the aggregate root. Slots are loaded together with the plan.
type MealPlan struct {
	ID          string
	Name        string
	StartDate   time.Time
	EndDate     time.Time
	IsPublished bool
	Slots       []MealSlot
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewMealPlan validates and builds a plan.
func NewMealPlan(id, name string, startDate, endDate time.Time, isPublished bool, slots []MealSlot) (*MealPlan, error) {
	if id == "" {
		return nil, fmt.Errorf("meal plan id cannot be empty")
	}
	if endDate.Before(startDate) {
		return nil, fmt.Errorf("end date cannot be before start date")
	}
	if slots == nil {
		slots = []MealSlot{}
	}
	for _, s := range slots {
		if !s.MealType.Valid() {
			return nil, fmt.Errorf("invalid meal type %q", s.MealType)
		}
		if s.Date.Before(startDate) || s.Date.After(endDate) {
			return nil, fmt.Errorf("slot date out of plan range")
		}
	}
	return &MealPlan{
		ID:          id,
		Name:        name,
		StartDate:   startDate,
		EndDate:     endDate,
		IsPublished: isPublished,
		Slots:       slots,
	}, nil
}

// mergeQuantities combines two free-text quantities. If both are simple
// numbers, they are summed (e.g. "2" + "1" → "3"); otherwise they are joined
// with " + " (e.g. "2 cups" isn't parsed at unit level — documented limitation).
func mergeQuantities(a, b string) string {
	if a == "" {
		return b
	}
	if b == "" {
		return a
	}
	fa, aerr := parseFloat(strings.TrimSpace(a))
	fb, berr := parseFloat(strings.TrimSpace(b))
	if aerr == nil && berr == nil {
		return trimFloat(fa + fb)
	}
	return a + " + " + b
}

func parseFloat(s string) (float64, error) {
	return strconv.ParseFloat(s, 64)
}

func trimFloat(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%g", f)
}
