package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/diegobraga92/pudimproductivity/backend/internal/contexts/content/media"
)

// FilesystemUploader stores uploads on the local server disk. Unlike the S3
// uploader it does not issue presigned PUT URLs against an external object
// store; GenerateUploadURL returns a URL on this server's own media route
// (PUT /api/v1/media/{key}), and GET /api/v1/media/{key} serves the bytes.
// Keys are unguessable (uuid/filename, generated by the caller), which is the
// LAN-trusted equivalent of a short-lived presigned URL.
type FilesystemUploader struct {
	dir           string
	publicBaseURL string
}

// Compile-time check that FilesystemUploader satisfies the media.Storage port.
var _ media.Storage = (*FilesystemUploader)(nil)

// NewFilesystemUploader builds a local-disk uploader rooted at dir, creating
// the directory if missing. publicBaseURL is prefixed to returned upload URLs
// (default "/api/v1/media" — same-origin, so uploads flow through the
// frontend's /api proxy).
func NewFilesystemUploader(dir, publicBaseURL string) (*FilesystemUploader, error) {
	if dir == "" {
		return nil, fmt.Errorf("media: local media directory is required")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("media: create local media directory: %w", err)
	}
	if publicBaseURL == "" {
		publicBaseURL = "/api/v1/media"
	}
	return &FilesystemUploader{dir: dir, publicBaseURL: publicBaseURL}, nil
}

// GenerateUploadURL returns a PUT URL on this server's media route for key.
// The key is validated so the resolved path stays inside the media root.
func (u *FilesystemUploader) GenerateUploadURL(_ context.Context, key, _ string, _ time.Duration) (*media.UploadURL, error) {
	if err := media.ValidateKey(key); err != nil {
		return nil, fmt.Errorf("media: invalid object key: %w", err)
	}
	return &media.UploadURL{
		URL: fmt.Sprintf("%s/%s", strings.TrimRight(u.publicBaseURL, "/"), key),
		Key: key,
	}, nil
}

// Dir returns the local storage root.
func (u *FilesystemUploader) Dir() string { return u.dir }

// Get implements media.Storage for the local filesystem.
func (u *FilesystemUploader) Get(ctx context.Context, key string) (*media.File, error) {
	if err := media.ValidateKey(key); err != nil {
		return nil, err
	}
	f, err := os.Open(u.resolve(key))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, media.ErrNotFound
		}
		return nil, fmt.Errorf("media: read local object %q: %w", key, err)
	}
	st, statErr := f.Stat()
	if statErr != nil {
		return nil, fmt.Errorf("media: stat local object %q: %w", key, statErr)
	}
	return &media.File{Key: key, Content: f, Size: st.Size()}, nil
}

// Put implements media.Storage for the local filesystem.
func (u *FilesystemUploader) Put(ctx context.Context, key, _ string, r io.Reader) error {
	if err := media.ValidateKey(key); err != nil {
		return err
	}
	path := u.resolve(key)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("media: create local object directory: %w", err)
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		return fmt.Errorf("media: open local object %q for write: %w", key, err)
	}
	defer func() { _ = f.Close() }()
	if _, err := io.Copy(f, r); err != nil {
		return fmt.Errorf("media: write local object %q: %w", key, err)
	}
	return nil
}

// Delete implements media.Storage for the local filesystem.
func (u *FilesystemUploader) Delete(ctx context.Context, key string) error {
	if err := media.ValidateKey(key); err != nil {
		return err
	}
	err := os.Remove(u.resolve(key))
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("media: delete local object %q: %w", key, err)
	}
	return nil
}

// resolve returns the absolute path for key under the media root.
func (u *FilesystemUploader) resolve(key string) string {
	return filepath.Join(u.dir, filepath.FromSlash(key))
}
