package media

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"
)

// FilesystemUploader stores uploads on the local server disk. Unlike the S3
// uploader it does not issue presigned PUT URLs against an external object
// store; GenerateUploadURL returns a URL on this server's own media route
// (PUT /api/v1/media/{key}), and GET /api/v1/media/{key} serves the bytes.
// Keys are unguessable (uuid/filename, generated by the caller), which is the
// LAN-trusted equivalent of a short-lived presigned URL.
type FilesystemUploader struct {
	dir           string
	publicBaseURL string
}

// NewFilesystemUploader builds a local-disk uploader rooted at dir, creating
// the directory if missing. publicBaseURL is prefixed to returned upload URLs
// (default "/api/v1/media" — same-origin, so uploads flow through the
// frontend's /api proxy).
func NewFilesystemUploader(dir, publicBaseURL string) (*FilesystemUploader, error) {
	if dir == "" {
		return nil, fmt.Errorf("media: local media directory is required")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("media: create local media directory: %w", err)
	}
	if publicBaseURL == "" {
		publicBaseURL = "/api/v1/media"
	}
	return &FilesystemUploader{dir: dir, publicBaseURL: publicBaseURL}, nil
}

// GenerateUploadURL returns a PUT URL on this server's media route for key.
// The key is validated so the resolved path stays inside the media root.
func (u *FilesystemUploader) GenerateUploadURL(_ context.Context, key, _ string, _ time.Duration) (*UploadURL, error) {
	if err := ValidateKey(key); err != nil {
		return nil, fmt.Errorf("media: invalid object key: %w", err)
	}
	return &UploadURL{
		URL: fmt.Sprintf("%s/%s", strings.TrimRight(u.publicBaseURL, "/"), key),
		Key: key,
	}, nil
}

// Dir returns the local storage root.
func (u *FilesystemUploader) Dir() string { return u.dir }

// ValidateKey rejects object keys that could escape the media root (path
// traversal) or reference non-file segments. The allowed shape is one or more
// safe path segments, e.g. "<uuid>/pancakes.jpg".
func ValidateKey(key string) error {
	if key == "" || strings.Contains(key, "..") || strings.HasPrefix(key, "/") || strings.HasSuffix(key, "/") {
		return fmt.Errorf("unsafe key %q", key)
	}
	for _, part := range strings.Split(key, "/") {
		if part == "" || part == "." || part == ".." {
			return fmt.Errorf("unsafe key %q", key)
		}
		for _, r := range part {
			if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '.' || r == '-' || r == '_') {
				return fmt.Errorf("unsafe key %q", key)
			}
		}
	}
	return nil
}
