-- Phase 5a: Recipes module. Recipes are the composable unit for meal planning
-- (Phase 5): a meal-plan slot references a recipe, and the shopping list is
-- generated by aggregating recipe_ingredients across slotted recipes.
CREATE TABLE IF NOT EXISTS recipes (
    id                 UUID PRIMARY KEY,
    title              TEXT NOT NULL,
    description        TEXT NOT NULL DEFAULT '',
    difficulty         TEXT NOT NULL DEFAULT 'easy'
        CHECK (difficulty IN ('easy', 'medium', 'hard')),
    prep_time_minutes  INT  NOT NULL DEFAULT 0 CHECK (prep_time_minutes >= 0),
    cook_time_minutes  INT  NOT NULL DEFAULT 0 CHECK (cook_time_minutes >= 0),
    servings           INT  NOT NULL DEFAULT 1 CHECK (servings >= 1),
    image_url          TEXT,
    source_url         TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recipe_tags (
    recipe_id UUID NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    tag       TEXT NOT NULL,
    PRIMARY KEY (recipe_id, tag)
);
-- Tag filter + tag dedupe in list queries.
CREATE INDEX IF NOT EXISTS idx_recipe_tags_tag ON recipe_tags (tag);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
    id         UUID PRIMARY KEY,
    recipe_id  UUID NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    quantity   TEXT NOT NULL DEFAULT '',
    unit       TEXT NOT NULL DEFAULT '',
    sort_order INT  NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe ON recipe_ingredients (recipe_id);

CREATE TABLE IF NOT EXISTS recipe_steps (
    id          UUID PRIMARY KEY,
    recipe_id   UUID NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    step_number INT  NOT NULL,
    instruction TEXT NOT NULL,
    UNIQUE (recipe_id, step_number)
);
CREATE INDEX IF NOT EXISTS idx_recipe_steps_recipe ON recipe_steps (recipe_id);
