-- Phase 5: Meal planning. A meal plan is a week-ish grid of slots; each slot
-- references a recipe (Phase 5a). The shopping list is generated by
-- aggregating ingredients across the slotted recipes.
CREATE TABLE IF NOT EXISTS meal_plans (
    id           UUID PRIMARY KEY,
    name         TEXT NOT NULL DEFAULT '',
    start_date   DATE NOT NULL,
    end_date     DATE NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS meal_plan_slots (
    id           UUID PRIMARY KEY,
    meal_plan_id UUID NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
    date         DATE NOT NULL,
    meal_type    TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')),
    recipe_id    UUID REFERENCES recipes(id) ON DELETE SET NULL,
    notes        TEXT NOT NULL DEFAULT '',
    UNIQUE (meal_plan_id, date, meal_type)
);
CREATE INDEX IF NOT EXISTS idx_meal_plan_slots_plan ON meal_plan_slots (meal_plan_id);

CREATE TABLE IF NOT EXISTS meal_plan_shopping_list (
    id              UUID PRIMARY KEY,
    meal_plan_id    UUID NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
    ingredient_name TEXT NOT NULL,
    quantity_agg    TEXT NOT NULL DEFAULT '',
    unit            TEXT NOT NULL DEFAULT '',
    is_checked      BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (meal_plan_id, ingredient_name, unit)
);
CREATE INDEX IF NOT EXISTS idx_meal_plan_shopping_plan ON meal_plan_shopping_list (meal_plan_id);
