#!/usr/bin/env node
/**
 * Single source of truth for the app version: the repository-root `VERSION`
 * file. This script propagates it to every place that needs the version as a
 * literal, so releasing only ever touches one file:
 *
 *   echo 1.2.0 > VERSION
 *   node scripts/sync-version.mjs           # propagate
 *   node scripts/sync-version.mjs --check   # fail if anything drifted (CI)
 *
 * Why materialise at all instead of reading VERSION everywhere:
 *   - electron-builder and Electron's `app.getVersion()` require a real
 *     `desktop/package.json#version`; npm lockfiles repeat it.
 *   - Go's `//go:embed` cannot reach outside the module directory, so the
 *     backend keeps a generated copy under internal/version/.
 *   - The health OpenAPI spec documents the app version as a response example,
 *     and the generated TypeScript client embeds it as a JSDoc `@example`.
 *
 * Consumers that can read VERSION directly do so and are intentionally absent
 * from the target list: mobile/app/build.gradle.kts and web/vite.config.ts.
 *
 * CI runs `--check` (see .github/workflows/web-ci.yml and scripts/ci-check.sh)
 * so the copies can never silently drift from VERSION.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

/** Reads a file, treating a missing file as empty (targets may not exist yet). */
function readFileOrEmpty(path) {
  try {
    return readFileSync(path, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return "";
    throw error;
  }
}

/** Reads the canonical VERSION file, validating that it holds plain semver. */
function readCanonicalVersion() {
  const version = readFileOrEmpty(join(root, "VERSION")).trim();
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    console.error(
      `[version] VERSION must hold plain semver (MAJOR.MINOR.PATCH), got ${JSON.stringify(version)}`,
    );
    process.exit(1);
  }
  return version;
}

/**
 * Replaces the first `count` `"version": "..."` fields in an npm file. In a
 * lockfile the first two belong to the root package (top level and
 * `packages[""]`); every later one describes a dependency and is left alone.
 */
function rewriteNpmVersionFields(text, version, count) {
  let seen = 0;
  return text.replace(/"version": "[^"]*"/g, (match) => {
    seen += 1;
    return seen <= count ? `"version": "${version}"` : match;
  });
}

const GENERATED_BANNER =
  "// Code generated by scripts/sync-version.mjs from VERSION — do not edit.\n";

/** Replaces a single occurrence, failing loudly when the pattern is absent. */
function replaceOnce(text, pattern, replacement, label) {
  if (!pattern.test(text)) {
    throw new Error(`[version] could not find ${label} (expected ${pattern})`);
  }
  return text.replace(pattern, replacement);
}

/** [path relative to the repo root, (currentContents, version) => nextContents]. */
const targets = [
  ["desktop/package.json", (text, v) => rewriteNpmVersionFields(text, v, 1)],
  ["web/package.json", (text, v) => rewriteNpmVersionFields(text, v, 1)],
  ["desktop/package-lock.json", (text, v) => rewriteNpmVersionFields(text, v, 2)],
  ["web/package-lock.json", (text, v) => rewriteNpmVersionFields(text, v, 2)],
  // Default applied by backend/internal/platform/config when VERSION is unset;
  // embedded via //go:embed by backend/internal/version/version.go.
  ["backend/internal/version/version.txt", (_text, v) => v],
  [
    "desktop/src/generated-version.ts",
    (_text, v) => `${GENERATED_BANNER}export const APP_VERSION = "${v}";\n`,
  ],
  // The health spec is the only place a spec documents the app version; its
  // TypeScript client (npm run generate:api) embeds the same value as JSDoc.
  // Keeping both derived keeps `npm run check:api` green after a bump.
  [
    "api/openapi/health-v1.yaml",
    (text, v) =>
      replaceOnce(text, /example: "\d+\.\d+\.\d+"/, `example: "${v}"`, "the health spec version example"),
  ],
  [
    "web/src/api/generated/health-v1.ts",
    (text, v) =>
      replaceOnce(text, /@example \d+\.\d+\.\d+/, `@example ${v}`, "the generated health client @example"),
  ],
];

const version = readCanonicalVersion();
const drifted = [];

for (const [relativePath, transform] of targets) {
  const path = join(root, relativePath);
  const current = readFileOrEmpty(path);
  let next;
  try {
    next = transform(current, version);
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
  if (current === next) continue;

  drifted.push(relativePath);
  if (!check) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, next);
    console.log(`[version] ${relativePath} -> ${version}`);
  }
}

if (check && drifted.length > 0) {
  console.error(`[version] out of sync with VERSION (${version}):`);
  for (const relativePath of drifted) console.error(`  - ${relativePath}`);
  console.error("[version] run: node scripts/sync-version.mjs");
  process.exit(1);
}

console.log(
  check
    ? `[version] all ${targets.length} targets in sync (${version})`
    : `[version] ${version} propagated to ${targets.length} targets`,
);
