name: Build and Push Images

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend
        run: |
          docker build \
            -f backend/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/opentodo-backend:latest \
            .

      - name: Push backend
        run: docker push ghcr.io/${{ github.repository_owner }}/opentodo-backend:latest

      - name: Build web
        run: |
          docker build \
            -f web/Dockerfile \
            --build-arg VITE_API_URL=http://192.168.3.12:3000 \
            -t ghcr.io/${{ github.repository_owner }}/opentodo-web:latest \
            .

      - name: Push web
        run: docker push ghcr.io/${{ github.repository_owner }}/opentodo-web:latest


  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > release.keystore

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build Signed Release APK
        working-directory: android
        run: |
          export KEYSTORE_FILE=$GITHUB_WORKSPACE/release.keystore
          export KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          export KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          export KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          export VERSION_CODE=${{ github.run_number }}
          ./gradlew assembleRelease

      - name: List generated APKs
        run: find android -name "*.apk"

      - name: Delete existing dev release (if exists)
        run: |
          gh release delete dev -y || true
          git push origin :refs/tags/dev || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new dev release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev
          name: Dev Build (Latest)
          prerelease: true
          files: android/**/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# TODO
